"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = os.environ.get('SECRET_KEY', 'your-local-dev-key-here')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# ALLOWED_HOSTS = ['*']
ALLOWED_HOSTS = ['web-production-405e6.up.railway.app', '127.0.0.1', 'localhost']


JAZZMIN_SETTINGS = {
    # Browser tab title
    "site_title": "Rikhil Admin",

    # Top of the login page
    "site_header": "Rikhil Portfolio",

    # Brand name in the sidebar
    "site_brand": "Rikhil.dev",

    # Welcome text on login page
    "welcome_sign": "Welcome back, Rikhil",

    # Copyright in footer
    "copyright": "Kakani Rikhil",

    # Top menu links
    "topmenu_links": [
        {"name": "View Portfolio", "url": "/", "new_window": True},
        {"name": "Contact Messages", "model": "portfolio.contactmessage"},
    ],

    # Sidebar icons for each model
    "icons": {
        "auth":                     "fas fa-users-cog",
        "auth.user":                "fas fa-user",
        "auth.Group":               "fas fa-users",
        "portfolio.Profile":        "fas fa-id-card",
        "portfolio.Project":        "fas fa-code",
        "portfolio.Skill":          "fas fa-star",
        "portfolio.Experience":     "fas fa-briefcase",
        "portfolio.Education":      "fas fa-graduation-cap",
        "portfolio.Certification":  "fas fa-certificate",
    },

    # Default icon for models without a custom one
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-circle",

    # Use Font Awesome icons
    "related_modal_active": True,

    # Color theme — options: default, cerulean, cosmo, flatly,
    #               journal, litera, lumen, lux, materia,
    #               minty, pulse, sandstone, simplex, sketchy,
    #               slate, solar, spacelab, superhero, united, yeti
    "theme": "darkly",

    # Dark mode sidebar
    "dark_mode_theme": "darkly",

    # Hide these from the sidebar
    "hide_apps": [],
    "hide_models": [],

    # Order of apps in sidebar
    "order_with_respect_to": [
        "portfolio",
        "portfolio.Profile",
        "portfolio.Project",
        "portfolio.Skill",
        "portfolio.Experience",
        "portfolio.Education",
        "portfolio.Certification",
        "auth",
    ],

    # Show UI customizer button in admin
    "show_ui_builder": True,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text":   False,
    "brand_small_text":  False,
    "brand_colour":      False,
    "accent":            "accent-primary",
    "navbar":            "navbar-dark",
    "no_navbar_border":  True,
    "navbar_fixed":      True,
    "layout_boxed":      False,
    "footer_fixed":      False,
    "sidebar_fixed":     True,
    "sidebar":           "sidebar-dark-primary",
    "sidebar_nav_small_text":    False,
    "sidebar_disable_expand":    False,
    "sidebar_nav_child_indent":  True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style":  False,
    "sidebar_nav_flat_style":    False,
    "theme":             "darkly",
    "dark_mode_theme":   "darkly",
    "button_classes": {
        "primary":   "btn-primary",
        "secondary": "btn-secondary",
        "info":      "btn-outline-info",
        "warning":   "btn-warning",
        "danger":    "btn-danger",
        "success":   "btn-success",
    },
}

# Application definition

INSTALLED_APPS = [
    'jazzmin',  
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'portfolio'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Email settings
EMAIL_BACKEND   = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST      = 'smtp.gmail.com'
EMAIL_PORT      = 587
EMAIL_USE_TLS   = True
EMAIL_HOST_USER     = 'kakanirikhil7@gmail.com'   # your Gmail address
EMAIL_HOST_PASSWORD = 'fgcs nxbc tios hyxf'   # Gmail App Password (NOT your login password)

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'portfolio.context_processors.profile',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

import os


# Whitenoise static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Static files
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'portfolio/static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # used when deploying

# Media files (user uploads like project images)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
