# Generated by Django 6.0.5 on 2026-05-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='preview_image',
            field=models.ImageField(blank=True, upload_to='certificates/previews/'),
        ),
    ]
